package WarriorCulturesShaolin.Scoped.com.github.core.handler;

import java.io.File;
import java.util.logging.Level;

import net.minecraftforge.common.Configuration;

import WarriorCulturesShaolin.Scoped.com.github.lib.BlockIDs;
import WarriorCulturesShaolin.Scoped.com.github.lib.ItemIDs;
import WarriorCulturesShaolin.Scoped.com.github.lib.Reference;
import WarriorCulturesShaolin.Scoped.com.github.lib.Strings;

import cpw.mods.fml.common.FMLLog;

public class ConfigurationHandler
{
	public static Configuration config;
	
	public static void init(File file)
	{
		config = new Configuration(file);
		
		try
		{
			config.load();
			
			/**
			 * Block Configuration
			 */
			BlockIDs.BLOCK_BAMBOOBLOCK_ID = config.getBlock(Strings.BLOCK_BAMBOOBLOCK_NAME, BlockIDs.BLOCK_BAMBOOBLOCK_ID_DEFAULT).getInt(BlockIDs.BLOCK_BAMBOOBLOCK_ID_DEFAULT);
			BlockIDs.BLOCK_PLANKS_CHERRYWOOD_ID = config.getBlock(Strings.BLOCK_PLANKS_CHERRYWOOD_NAME, BlockIDs.BLOCK_PLANKS_CHERRYWOOD_ID_DEFAULT).getInt(BlockIDs.BLOCK_PLANKS_CHERRYWOOD_ID_DEFAULT);
			BlockIDs.BLOCKHALFSLAB_BAMBOOSINGLESLAB_ID = config.getBlock(Strings.BLOCKHALFSLAB_SINGLEBAMBOO_NAME, BlockIDs.BLOCKHALFSLAB_BAMBOOSINGLESLAB_ID_DEFAULT).getInt(BlockIDs.BLOCKHALFSLAB_BAMBOOSINGLESLAB_ID_DEFAULT);
			BlockIDs.BLOCKHALFSLAB_BAMBOODOUBLESLAB_ID = config.getBlock(Strings.BLOCKHALFSLAB_DOUBLEBAMBOO_NAME, BlockIDs.BLOCKHALFSLAB_BAMBOODOUBLESLAB_ID_DEFAULT).getInt(BlockIDs.BLOCKHALFSLAB_BAMBOODOUBLESLAB_ID_DEFAULT);
			BlockIDs.BLOCKHALFSLAB_CHERRYPLANKSSINGLESLAB_ID = config.getBlock(Strings.BLOCKHALFSLAB_SINGLECHERRYWOOD_NAME, BlockIDs.BLOCKHALFSLAB_CHERRYPLANKSSINGLESLAB_ID_DEFAULT).getInt(BlockIDs.BLOCKHALFSLAB_CHERRYPLANKSSINGLESLAB_ID_DEFAULT);
			BlockIDs.BLOCKHALFSLAB_CHERRYPLANKSDOUBLESLAB_ID = config.getBlock(Strings.BLOCKHALFSLAB_DOUBLECHERRYWOOD_NAME, BlockIDs.BLOCKHALFSLAB_CHERRYPLANKSDOUBLESLAB_ID_DEFAULT).getInt(BlockIDs.BLOCKHALFSLAB_CHERRYPLANKSDOUBLESLAB_ID_DEFAULT);
			BlockIDs.BLOCKHALFSLAB_THATCHSINGLESLAB_ID = config.getBlock(Strings.BLOCKHALFSLAB_SINGLETHATCH_NAME, BlockIDs.BLOCKHALFSLAB_THATCHSINGLESLAB_ID_DEFAULT).getInt(BlockIDs.BLOCKHALFSLAB_THATCHSINGLESLAB_ID_DEFAULT);
			BlockIDs.BLOCKHALFSLAB_THATCHDOUBLESLAB_ID = config.getBlock(Strings.BLOCKHALFSLAB_DOUBLETHATCH_NAME, BlockIDs.BLOCKHALFSLAB_THATCHDOUBLESLAB_ID_DEFAULT).getInt(BlockIDs.BLOCKHALFSLAB_THATCHDOUBLESLAB_ID_DEFAULT);
			BlockIDs.BLOCK_PANE_BAMBOOPAPERWALL_ID = config.getBlock(Strings.BLOCK_PANE_BAMBOOPAPERWALL_NAME, BlockIDs.BLOCK_PANE_BAMBOOPAPERWALL_ID_DEFAULT).getInt(BlockIDs.BLOCK_PANE_BAMBOOPAPERWALL_ID_DEFAULT);
			BlockIDs.BLOCK_PANE_CHERRYPAPERWALL_ID = config.getBlock(Strings.BLOCK_PANE_CHERRYPAPERWALL_NAME, BlockIDs.BLOCK_PANE_CHERRYPAPERWALL_ID_DEFAULT).getInt(BlockIDs.BLOCK_PANE_CHERRYPAPERWALL_ID_DEFAULT);
			BlockIDs.BLOCK_GLASSBLOCK_ID = config.getBlock(Strings.BLOCK_GLASSBLOCK_NAME, BlockIDs.BLOCK_GLASSBLOCK_ID_DEFAULT).getInt(BlockIDs.BLOCK_GLASSBLOCK_ID_DEFAULT);
			BlockIDs.BLOCK_THATCHBLOCK_ID = config.getBlock(Strings.BLOCK_THATCHBLOCK_NAME, BlockIDs.BLOCK_THATCHBLOCK_ID_DEFAULT).getInt(BlockIDs.BLOCK_THATCHBLOCK_ID_DEFAULT);
			
			/**
			 * Item Configuration
			 */
			ItemIDs.ITEM_SHAOLIN_DAO_ID = config.getItem(Strings.ITEM_SHAOLIN_DAO_NAME, ItemIDs.ITEM_SHAOLIN_DAO_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_DAO_ID_DEFAULT);
			
			ItemIDs.ITEM_SHAOLIN_DAO_ID = config.getItem(Strings.ITEM_SHAOLIN_DAO_NAME, ItemIDs.ITEM_SHAOLIN_DAO_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_DAO_ID_DEFAULT);
			ItemIDs.ITEM_MONK_SWORD_ID = config.getItem(Strings.ITEM_MONK_SWORD_NAME, ItemIDs.ITEM_MONK_SWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_MONK_SWORD_ID_DEFAULT);
			ItemIDs.ITEM_MONK_HOOKBLADE_ID = config.getItem(Strings.ITEM_MONK_HOOK_NAME, ItemIDs.ITEM_MONK_HOOKBLADE_ID_DEFAULT).getInt(ItemIDs.ITEM_MONK_HOOKBLADE_ID_DEFAULT);
			ItemIDs.ITEM_SHAOLIN_SHEARS_ID = config.getItem(Strings.ITEM_SHAOLIN_SHEARS_NAME, ItemIDs.ITEM_SHAOLIN_SHEARS_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_SHEARS_ID_DEFAULT);
			ItemIDs.ITEM_SHAOLIN_MACHETE_ID = config.getItem(Strings.ITEM_SHAOLIN_MACHETE_NAME, ItemIDs.ITEM_SHAOLIN_MACHETE_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_MACHETE_ID_DEFAULT);
			ItemIDs.ITEM_SHAOLIN_BUTTERFLY_ID = config.getItem(Strings.ITEM_SHAOLIN_BUTTERFLY_NAME, ItemIDs.ITEM_SHAOLIN_BUTTERFLY_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BUTTERFLY_ID_DEFAULT);
			ItemIDs.ITEM_SHAOLIN_RISINGSUN_ID = config.getItem(Strings.ITEM_SHAOLIN_RISINGSUN_NAME, ItemIDs.ITEM_SHAOLIN_RISINGSUN_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_RISINGSUN_ID_DEFAULT);
			
			/**
			 * Tools
			 */
			ItemIDs.ITEM_SHAOLIN_SHOVEL_ID = config.getItem(Strings.ITEM_SHAOLIN_SHOVEL_NAME, ItemIDs.ITEM_SHAOLIN_SHOVEL_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_SHOVEL_ID_DEFAULT);
			
			/**
			 * Armor
			 */
			ItemIDs.ITEM_SHAOLIN_LEGS_ID = config.getItem(Strings.ITEM_SHAOLIN_STUDENT_LEGS_NAME, ItemIDs.ITEM_SHAOLIN_STUDENT_LEGS_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_STUDENT_LEGS_ID_DEFAULT);
			ItemIDs.ITEM_SHAOLIN_ROBE_ID = config.getItem(Strings.ITEM_SHAOLIN_STUDENT_ROBE_NAME, ItemIDs.ITEM_SHAOLIN_STUDENT_ROBE_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_STUDENT_ROBE_ID_DEFAULT);
			ItemIDs.ITEM_SHAOLIN_HEADBAND_ID = config.getItem(Strings.ITEM_SHAOLIN_STUDENT_HEADBAND_NAME, ItemIDs.ITEM_SHAOLIN_STUDENT_HEADBAND_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_STUDENT_HEADBAND_ID_DEFAULT);
			ItemIDs.ITEM_SHAOLIN_SHOES_ID = config.getItem(Strings.ITEM_SHAOLIN_STUDENT_SHOES_NAME, ItemIDs.ITEM_SHAOLIN_STUDENT_SHOES_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_STUDENT_SHOES_ID_DEFAULT);
			/*
			ItemIDs.ITEM_SHAOLIN_HALBERD_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			ItemIDs.ITEM_SHAOLIN_SHEARS_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			
			ItemIDs.ITEM_MONK_RATTANHATSHIELD_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			ItemIDs.ITEM_MONK_ROBES_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			ItemIDs.ITEM_MONK_SHOES_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			ItemIDs.ITEM_MONK_PANTS_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			
			ItemIDs.ITEM_MONK_ROPEDART_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			ItemIDs.ITEM_MONK_HOOKBLADE_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			ItemIDs.ITEM_MONK_SWORD_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			ItemIDs.ITEM_MONK_MASTERSTAFF_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			
			ItemIDs.ITEM_MONK_SPEAR_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			ItemIDs.ITEM_MONK_POLEARM_ID = config.getItem(Strings.ITEM_SHAOLIN_BROADSWORD_NAME, ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT).getInt(ItemIDs.ITEM_SHAOLIN_BROADSWORD_ID_DEFAULT);
			*/
		}
		catch(Exception e)
		{
			FMLLog.log(Level.SEVERE, e, Reference.MOD_ID + "Has a problem loading the cofig file!");
		}
		finally
		{
			config.save();
		}
	}
}
